Add Python-script and update README accordingly
mclang/nextcloud-deck-import-trello-json pull request #1
Opened 2020-04-12 18:09 UTC by jmcwine

2020-04-13 18:07 UTC, mclang commented on README.md
> +Simple [Go](https://golang.org/)/Python script that can be used to import Trello boards from exported JSON files
Go and Python scripts

2020-04-13 18:08 UTC, mclang commented on import_trello_json_to_NC_Deck.py
> +response = requests.post('https://devel.elainft-notkeaksi.fi/index.php/apps/deck/api/v1.0/boards', auth = (user, pword), data=boardData )
Eikö URL pitäisi tulla siitä configista?

2020-04-13 18:10 UTC, mclang commented on import_trello_json_to_NC_Deck.py
> +url = data['url']
Nämä voisi olla kuvaavammat esim `deck_user` tai `api_user` jotta ei mahdollisesti myöhemmin sotkeudu esim stack/card käyttäjiin.

2020-04-13 18:12 UTC, mclang commented on import_trello_json_to_NC_Deck.py
> +cardurl = boardurl + '/%s/stacks/%s/cards'
Lieneekö pythonkin vakio nimeämistyyli `camelCase`, vaiko C tyylinen `snake_case`... Loppujen lopuksi sama kunhan käytät kaikkialla samanlaista nimeämistä niin helpompi lukea.

2020-04-13 18:14 UTC, mclang requested changes
Muuten hyvä :+1:

2020-04-14 07:23 UTC, mclang approved these changes

2020-04-14 07:40 UTC, jmcwine reviewed
Näkyskö nyt vastakommentit skripti-tiedostoon.

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +response = requests.post('https://devel.elainft-notkeaksi.fi/index.php/apps/deck/api/v1.0/boards', auth = (user, pword), data=boardData )
```suggestion
response = requests.post(boardUrl, auth = (user, pword), data=boardData )

```

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +cardurl = boardurl + '/%s/stacks/%s/cards'
```suggestion
boardUrl = url + 'boards'
stackUrl = boardUrl + '/%s/stacks'
cardUrl = boardUrl + '/%s/stacks/%s/cards'

```

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +url = stackurl % newboardId
```suggestion
url = stackUrl % newboardId

```

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +    url = cardurl % (newboardId, newstackId)
```suggestion
    url = cardUrl % (newboardId, newstackId)

```

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +pword = data['password']
```suggestion
apiUser = data['user']
apiPword = data['password']

```

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +pword = data['password']
Nojoo. Mutta miten minä pääsen tätä kautta muuttamaan koodia koko skriptistä? Tästä kommentoimalla ja ehdottamalla voin muuttaa vain noita sinun kommentoimia pätkiä?

2020-04-14 07:40 UTC, jmcwine commented on import_trello_json_to_NC_Deck.py
> +response = requests.post('https://devel.elainft-notkeaksi.fi/index.php/apps/deck/api/v1.0/boards', auth = (user, pword), data=boardData )
Pitäs joo, oli unohtunut muuttaa tuosta kohtaa. Jääkös tuo url nyt johonkin historiaan nähtäviin? Ainakin siellä minun forkissa se ehkä on, kai sen forkin voi jotenkin hävittää kun ei sitä enää tarvita jahka tämä PR saadaan setvittyä?

2020-04-14 07:45 UTC, mclang commented on import_trello_json_to_NC_Deck.py
> +response = requests.post('https://devel.elainft-notkeaksi.fi/index.php/apps/deck/api/v1.0/boards', auth = (user, pword), data=boardData )
Kyllä, kun tekee _squash_ mergen, joka niputtaa kaikki PR:n muutokset yhdeksi commitiksi ja tuhoaa sitten sen sinun puolen kokonaan.

2020-04-14 14:46 UTC, mclang approved these changes

2020-04-14 14:50 UTC, mclang commented on trello-data.json
> +{"id":"5e8d49a6a3f9161211889a61","name":"NC Import Testing Board","desc":"","descData":null,"closed":false,"idOrganization":null,"shortLink":"LZRVtLHW","powerUps":[],"dateLastActivity":"2020-04-08T03
Tuolla on muutamassa kohassa sinun etunimi nimi ja esim `jtlang1`... Jos omiani olis, niin ootasin pois :thinking:

2020-04-15 05:38 UTC, jmcwine commented on trello-data.json
> +{"id":"5e8d49a6a3f9161211889a61","name":"NC Import Testing Board","desc":"","descData":null,"closed":false,"idOrganization":null,"shortLink":"LZRVtLHW","powerUps":[],"dateLastActivity":"2020-04-08T03
No niin, puhdistin/muokkasin kaikki viittaukset käyttäjään ja urleihin.

2020-04-15 05:39 UTC, jmcwine reviewed
Oliskohan ne nyt kunnossa.

2020-04-15 05:48 UTC, mclang approved these changes

2020-04-15 05:49 UTC, merged